### ISSUE TITLE
Docker container not showing webui when lauched, instead going to GitHub repo

### ISSUE THREAD

**Issue by SmartPhoneLover** [orhun/rustypaste#12]
Hello, I would like to know if someone that has successufully installed RustPaste in Docker, experienced the same as me.

When, I launch the container, it simply redirects the webui to the GitHub repo (orhun/rustypaste).

Note: I used the config.toml file as it is, didn't modified anything. All things related to port redirection and so on, I do that via command.

What could be happening here?

**Comment by orhun** [comment]
Hello, that's an expected behavior. Rustypaste redirects to the repository if you don't give it a path. Try uploading a file.

**Comment by inglor** [comment]
@orhun maybe you can provide something like a landing page with man pages? Similar to http://ix.io/

**Comment by orhun** [comment]
Hey I'm closing this in favor of #13
