### ISSUE TITLE
Config ergonomics for turning off random URLs

### ISSUE THREAD

**Issue by ajbdev** [orhun/rustypaste#121]
This isn't that big of a deal, but the configuration is a little awkward for turning random URLs off.
Currently, in order to turn random URL's off, you must have at least one `random_url` declaration with a type and `enabled = false`. Ex:

```rs
random_url = { enabled = false, type = "petname" }
```

It took me a bit to figure this out when I was setting up my local instance.

Perhaps it might make sense to have another config property to turn off random URL names? Or allow `random_url  = { enabled = false }` with no type set?

**Comment by orhun** [comment]
Yeah, I totally agree. It is not very intuitive to set `enable` to `false` at first glance so we should definitely improve it.

Having another config property is an option but then we will be polluting the config file with an extra property just to disable a functionality. In that case, I would rather go with your second recommendation since we don't need to define another property.

Also, as another idea, how about removing the `enabled` field from the struct altogether and make it optional? So that you can disable this feature with just commenting out the property as follows:

```toml
# enabled
random_url = { type = "petname", words = 2, separator = "-" }

# disabled 
# random_url = { type = "petname", words = 2, separator = "-" }
```

What do you think?

cc @tessus for comments

**Comment by ajbdev** [comment]
Looks pretty intuitive to me, I think that would work just fine as long as its mentioned somewhere in the docs.

**Comment by tessus** [comment]
I didn't have any issues, since the `config.toml` had all examples included, so I only had to replace `true` with `false`.

However, I do understand @ajbdev's concern. I also like @orhun's suggestion to make `random_url` optional and removing the `enabled` field.

**Comment by orhun** [comment]
Just realized we can do the same for `delete_expired_files` 🙈

**Comment by tessus** [comment]
> Just realized we can do the same for `delete_expired_files` 🙈

True, but...

...it will be a pain in the ass to keep it backwards compatible.

**Comment by orhun** [comment]
What do you mean? Can't we do the same thing as `random_url`?

It is not a big deal though.

**Comment by tessus** [comment]
With random URL there were still other fields in the mix. But in this case, it'd be either:

# new

```
delete_expired_files = 1h
```

# old

```
delete_expired_files = { enabled = true, interval = "1h" }
```

So, how can we make Rust understand that the option is either a simple time duration or a struct? Both have to be valid to not inttroduce a breaking change.

**Comment by orhun** [comment]
Ah I see, I meant just removing the enabled field like this:

```toml
delete_expired_files = { interval = "1h" }
```

>  Both have to be valid to not inttroduce a breaking change.

Yeah..

**Comment by tessus** [comment]
That seem more like a hassle. I'd just wait for 1.0.0 and make a clear cut then, otherwise the code becomes too complex just to keep backwards compatibility. But it's your choice of course.

**Comment by orhun** [comment]
Makes sense.
