### ISSUE TITLE
DELETE end point

### ISSUE THREAD

**Issue by ajbdev** [orhun/rustypaste#127]
I'm using rustypaste on my LAN as a lightweight file server for transferring files/links/text across devices (currently I'm building the UI for it). One thing I realized rustypaste lacks which I would like to have is the ability to remove files and the ability to update files (change their contents or set a new expiration).

However, I'm aware that my use case may be niche and probably not something that would be included in most pastebin services, so before I set about building a PR for this I thought I'd see if this fits with the vision of the app enough to consider. If not I may just need to find a new backend service for my UI.

Interestingly I have found that there's not a lot out there in the ways of a simple file hosting service that have simple API access without a lot of other bells and whistles that I don't need. Most solutions are pretty heavy (like syncthing) which is why I ended up looking at pastebin services. Rustypaste fits quite nice in this regard with it's simple HTTP interface and speed. 

EDIT: thinking more on this, I think the only one I would truly need is DELETE.

**Comment by ajbdev** [comment]
In my use case anyone with access to the endpoint is trusted enough to delete any file. I wouldn't want to implement roles either. I know this usecase is probably niche though compared to normal pastebin use cases.

**Comment by tessus** [comment]
> In my use case anyone with access to the endpoint is trusted enough to delete any file. I wouldn't want to implement roles either. I know this usecase is probably niche though compared to normal pastebin use cases.

In that case I would still suggest to create a second token array. I know, this is not RBAC, but at least it gives you a little bit more control over who can delete files.

**Comment by tessus** [comment]
I think the easiest for now would be to add a new token array (`delate_tokens`) and an `expose_delete` config options. After that a `#[delete("/{file}")]` endpoint should do the trick.

For the future RBAC might be a nice side project, but will require some serious architectural work. Right now everything is very simple and just mapped to the filesystem. RBAC would require either additional meta data files or a database. In both cases all calls would require additional authn/authz calls and thus become more complex.

**Comment by orhun** [comment]
I agree, just one thing: can we possibly handle this with a single config option? e.g. when `delete_tokens` is set, we expose the delete endpoint or something similar. What do you think?

**Comment by tessus** [comment]
Yes, great idea. This makes perfect sense. No need for an `expose_` config option. I just thought along the same lines as the other 2 cases, but this one is certainly different. 👍

**Comment by orhun** [comment]
Great, I'm wondering if @ajbdev is interested in contributing this feature 🦀 or else @tessus can take this probably 🙈

**Comment by tessus** [comment]
Yep, I'm in. I'll let @ajbdev decide.

**Comment by tessus** [comment]
whenever you want me to continue or help out, just let me know. I'll be in CET starting mid-Setempber for an unspecified timeframe. This means I can work on stuff while you are having yuor good night's rest. ;-)

**Comment by ajbdev** [comment]
@tessus - I could definitely use that ;)

Here's my preliminary attempt at the implementation: https://github.com/orhun/rustypaste/compare/master...ajbdev:rustypaste:delete-endpoint-with-tokens
Since you are already setup as a contributor on my fork, feel free to change or add to it if you want to. I think this satisfies the main requirements but I'm not sure if the implementation will work. I can also go ahead and open the PR if you'd like to comment in that style, but I figured I'd give you the chance to make any changes first.

**Comment by ajbdev** [comment]
Sounds great! Here it is: https://github.com/orhun/rustypaste/pull/136
