### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by orhun** [orhun/rustypaste#13]
Show a cool 😎 landing page instead of redirecting to the repository when `/` is visited.

Some ideas:

- [http://ix.io/](http://ix.io/) (man page style)
- [https://0x0.st/](https://0x0.st/) (something simple)

**Comment by TheTechRobo** [comment]
Should it be configurable or included as a const?

**Comment by orhun** [comment]
> Should it be configurable or included as a const?

It should be both I think, we can have a default landing page and have it configurable in the config file. But handling it as a const is a good start.
