### ISSUE TITLE
How to setup authentication?

### ISSUE THREAD

**Issue by Nbelles** [orhun/rustypaste#14]
Hello,

I'm really liking the very minimalist-style setup of rustypaste so far. It's so much faster than everything else I've tried lately. 

I am curious if we could get some more documentation about how to use the authentication portion of rustypaste. How do we setup authentication on the server side? I think the documentation on how to use the authentication on the client side is clear but we'll find out once I figure out how to setup the server side authentication.

Thanks!

**Comment by inglor** [comment]
Check https://github.com/orhun/rustypaste/blob/master/.env file

**Comment by Nbelles** [comment]
That's not super helpful because I don't know what to set AUTH_TOKEN to.

**Comment by inglor** [comment]
It can be something random like the output of `openssl rand -base64 32`. Just make sure it's secret and you set the same on the client side.

**Comment by Nbelles** [comment]
Oh so we have to generate our own key that is shared between client and server? All the server does is check the key that the client sent against the one it has locally?

**Comment by Nbelles** [comment]
Is there a way to set the AUTH_TOKEN in the `config.toml` file? I'm currently running mine in a docker container and it would be easier to set it in the config file.

**Comment by inglor** [comment]
docker supports the .env file as per the README.md:
>  --env-file "$(pwd)/.env"

or docker-compose https://github.com/orhun/rustypaste/blob/master/docker-compose.yml#L10

**Comment by Nbelles** [comment]
This might be a stretch but would you know how to setup this in docker on Unraid? I really don't have much experience with custom configurations for docker containers on Unraid. I don't run any commands to start the docker container so I don't have a place that I would be able to add that argument to the start path. I also don't use docker-compose so I don't have a .yml file that I would edit to make that change.

**Comment by Nbelles** [comment]
I think I resolved it [here](https://github.com/SmartPhoneLover/unraid-docker-templates/issues/4#issuecomment-1049348228) actually. Thanks for the help!

**Comment by orhun** [comment]
Hey @Nbelles, I just released `0.6.3` and now you can set the auth token in the config file like this:

```toml
[server]
auth_token=""
```
