### ISSUE TITLE
Add hardened systemd service for running this

### ISSUE THREAD

**Issue by svenstaro** [orhun/rustypaste#16]
I think something like [miniserve's systemd unit file](https://github.com/svenstaro/miniserve/blob/master/packaging/miniserve%40.service) could easily be adapted.

**Comment by orhun** [comment]
Definitely a good idea!

@freswa told me that he's working on a PR to add a systemd service file in the following days.

**Comment by freswa** [comment]
I worked on the service file on the weekend. Based on this service file I put together for Arch
```

[Unit]
Description=Rustypaste server
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
User=rustypaste
Group=rustypaste
ExecStart=/usr/bin/rustypaste
ReadWritePaths=/var/lib/rustypaste
ReadOnlyPaths=/etc/rustypaste

WorkingDirectory=/var/lib/rustypaste
Environment="CONFIG=/etc/rustypaste/config.toml"
EnvironmentFile=/etc/rustypaste/rustypaste.env

# Hardening options
CapabilityBoundingSet=
AmbientCapabilities=
NoNewPrivileges=true
ProtectHome=true
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateTmp=true
PrivateDevices=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
```

I checked how we could adapt it for an instanciated service. Unfortunately, rustypaste requires the config file to be present to even start. So running rustypaste on any directory on the system would require a global config available. I hadn't had time to hack the configuration via cmd args together yet. Maybe we stick with the service file above for now? Otoh what is the use case for the instanciated service? Uploading pasted files to a random directory doesn't seem reasonable to me.

**Comment by orhun** [comment]
> I worked on the service file on the weekend. Based on this service file I put together for Arch

LGTM!

> I checked how we could adapt it for an instanciated service. Unfortunately, rustypaste requires the config file to be present to even start. So running rustypaste on any directory on the system would require a global config available.I hadn't had time to hack the configuration via cmd args together yet. Maybe we stick with the service file above for now?

Yes, I think it is fine to upload files under `/var/lib/rustypaste/upload` and restrict access to a specific user. (`rustypaste`)

> Otoh what is the use case for the instanciated service? Uploading pasted files to a random directory doesn't seem reasonable to me.

Currently I don't see much benefit in using an instantiated service.

@svenstaro any thoughts on this?

**Comment by svenstaro** [comment]
Let's start with a plain systemd service for now.

**Comment by orhun** [comment]
@freswa I tested the service file (through Arch package) and it seems to work fine. Can you submit it via PR?

**Comment by freswa** [comment]
Will create a PR later
