### ISSUE TITLE
Use `tracing` instead of `log`

### ISSUE THREAD

**Issue by orhun** [orhun/rustypaste#161]
Since `rustypaste` is a web service, it would be nice to integrate `tracing_subscriber::fmt` instead of plain logging via `env_logger`.

**Comment by woshilapin** [comment]
I'll try to make something about this one. Would you be interested in also converting `log` to `tracing`?

**Comment by orhun** [comment]
Yup, we should also use `tracing` instead of `log`. Can you make that change in the PR as well?

**Comment by woshilapin** [comment]
> Yup, we should also use `tracing` instead of `log`. Can you make that change in the PR as well?

@orhun OK, I indeed believe it's better, even if not necessary.
