### ISSUE TITLE
landing page form with authentication

### ISSUE THREAD

**Issue by classabbyamp** [orhun/rustypaste#183]
I'd like to add a landing page like the [example](https://github.com/orhun/rustypaste/blob/master/examples/landing_page.html), but I run rustypaste as a personal pastebin that only I should be able to upload to, and it seems the web form bypasses that restriction. Is there a way to restrict this kind of upload?

If it helps, I'm already running rustypaste behind a reverse proxy (traefik).

**Comment by orhun** [comment]
`0.14.2` is out along with this example!
