### ISSUE TITLE
Uploads are allowed to escape the `upload` directory using path traversal on the filename given

### ISSUE THREAD

**Issue by 5225225** [orhun/rustypaste#2]
`curl localhost:8000 -X POST -F "file=;filename=../."` will upload the data to the parent directory of `upload`. An attacker doesn't seem to have direct control over the filename given (unless random_url is disabled, in which case they can *freely* overwrite any file the web server has access to!), other than the extension, so they *probably* can't use this to overwrite important files, but this is still bad.

**Comment by orhun** [comment]
Thanks for reporting this 👍🏼
