### ISSUE TITLE
auth logging is too chatty

### ISSUE THREAD

**Issue by tessus** [orhun/rustypaste#209]
I think that the new auth logging is too chatty:

```rust
        } else if token_type == TokenType::Auth {
            // not configured `auth_tokens` means that the user is allowed to access the endpoints
            warn!("auth_tokens not configured, allowing the request without auth header");
            user_tokens.insert(token_type);
        }
```

Doesn't this mean that this is logged/printed for every request, if no auth_tokens are set? So, iff one doesn't use auth tokens, their log is spammed with these messages.

This shouldn't be a warning, rather an info message or debug message. IMO, there doesn't need to be a message at all.

**Comment by orhun** [comment]
I think this is a good point. Would you be down to create a PR to remove the log message?
