### ISSUE TITLE
502 if you add an extra /

### ISSUE THREAD

**Issue by repomansez** [orhun/rustypaste#303]
I just configured an instance of rustypaste on my website, and when testing it I noticed that if I add an extra / at the end of the URL, I get 502'd. Remove it, and it works as expected.

curl -F 'file=@example.txt' https://repomansez.xyz/upload - Works
curl -F 'file=@example.txt' https://repomansez.xyz/upload/ - Does not work

I'm not sure if that's a bug or if it's me screwing something up.

Also even if I try to navigate to https://repomansez.xyz/upload/ on my browser I get 404'd. Same thing if I do it locally.

**Comment by orhun** [comment]
I can't reproduce this with my own instance & locally. Is there a chance that you might have some proxy settings on your server maybe?

Also, have you checked out [rpaste](https://github.com/orhun/rustypaste-cli/) yet? 🐻

**Comment by repomansez** [comment]
> I can't reproduce this with my own instance & locally. Is there a chance that you might have some proxy settings on your server maybe?
Only thing related to that is nginx's reverse proxy, which I copypasted from your example
	location /upload {
        proxy_pass                         http://localhost:8011/;
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-For   $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-XSS-Protection        "1; mode=block";
        add_header X-Frame-Options         "sameorigin";
        add_header X-Content-Type-Options  "nosniff";
	}
> Also, have you checked out [rpaste](https://github.com/orhun/rustypaste-cli/) yet? 🐻
Yes! And it's what I use, I'm more concerned about someone trying to use my thingie and presuming it's broken because of the extra /

**Comment by orhun** [comment]
I see.

I have the exact same set up but I cannot reproduce it :/ Maybe @tessus can also have a look

**Comment by tessus** [comment]
I can't reproduce this either, but it looks like a reverse proxy config issue. I am using Apache, and my config looks like this:

```apache
ProxyPass        /upload              http://localhost:1111
ProxyPassReverse /upload              http://localhost:1111
```

No slashes at the end.

**Comment by repomansez** [comment]
> I can't reproduce this either, but it looks like a reverse proxy config issue. I am using Apache, and my config looks like this:
> 
> ```apache-config
> ProxyPass        /upload              http://localhost:1111
> ProxyPassReverse /upload              http://localhost:1111
> ```
> 
> No slashes at the end.

Just tested it here and removing the backslash from nginx's reverse proxy makes https://repomansez.xyz/upload say file is not found or expired :(

and I still get 404 if I add the extra /

**Comment by tessus** [comment]
Apache and nginx behave differently with default configs when it comes to adding slashes. So do browsers, btw.

Unfortunately I cannot reproduce the issue on my end. I am using Apache and the config I sent you works for me. I tried both of your curl commands and both work for me.

**Comment by repomansez** [comment]
Maybe it has more to do with nginx than with rustypaste. I'll have to do some research.

**Comment by repomansez** [comment]
Some further testing proved that it is in fact Nginx's fault.

location upload { makes upload/ 404 
while location upload/ { makes upload 404

I will therefore close this issue as it is unrelated to Rustypaste, thanks for the help!
