### ISSUE TITLE
Loading Auth Tokens from a file

### ISSUE THREAD

**Issue by Nydragon** [orhun/rustypaste#338]
I am using [agenix](https://github.com/ryantm/agenix) to encrypt my secrets. Agenix only exposes the path to the decrypted file, and not the content itself, necessitating to give an application the path to the file at runtime.

Since rustypaste either loads the auth token from the `AUTH_TOKEN` env var or the configuration file, I find myself unable to pass multiple auth tokens to the server.

I'd be interested in adding the parsing of an authentication file at server start, this authentication file could be provided via an `AUTH_FILE` env var, which holds the path, and the file itself could have a newline separated list of authentication tokens.

If there is a different or better method of implementing this feature I'd gladly hear about it.

**Comment by Nydragon** [comment]
Thanks for the reply!

Yes I did but that doesn't work with multiple token from my understanding, or is it possible to declare AUTH_TOKEN multiple times inside the .env?

**Comment by Nydragon** [comment]
I have added the parsing of an auth/del token file to my fork and would then submit them as a PR

**Comment by orhun** [comment]
> Yes I did but that doesn't work with multiple token from my understanding, or is it possible to declare AUTH_TOKEN multiple times inside the .env?

Ah I see. I don't think it support multiple tokens as of this moment.

> I have added the parsing of an auth/del token file to my fork and would then submit them as a PR if that is alright with you?

Yes, please go ahead!

**Comment by Nydragon** [comment]
Just opened a PR, also updated the README to reflect this new feature!
