### ISSUE TITLE
Network Error: Broken pipe when uploading a big file

### ISSUE THREAD

**Issue by repomansez** [orhun/rustypaste#340]
I tried to upload a 3.9G zip file but when it was about 350m in I got Network Error: Broken pipe (os error 32)`

I thought it could be nginx but client max body size is set to 10000M, and rustypaste's max_content_lenght is set to 5000M

**Comment by repomansez** [comment]
Update: while testing I tried pasting a file that was roughly 350M and I got a cloudflare "Request Entity is too large" error, so this may be nothing but cloudflare being ass :(

**Comment by orhun** [comment]
ah damn :/

let me know if this is a rustypaste-related issue and we can look into it.
