### ISSUE TITLE
Support one shot urls

### ISSUE THREAD

**Issue by vihu** [orhun/rustypaste#38]
Hello,

Thank you for this nice little crate, it's very useful!

I was wondering if you could add support for one shot urls. There is support for oneshot files and urls individually, but not for oneshot urls as I understand it. For example:

Both these work as intended: `$ rpaste -u "https://github.com"` and `$ rpaste -o foo.txt`

But this does not: `$ rpaste -o "https://google.com"`
Neither does this: `$ rpase -o -u "https://amazon.com"` (Well it works but doesn't make the url one shot).

Another way would be to introduce a brand new category `OneshotUrl` or something similar and have rpaste expose a different flag for it. I have started some work on doing that [here](https://github.com/orhun/rustypaste/compare/master...vihu:rustypaste:rg/oneshot-url).

**Comment by orhun** [comment]
Hey! 🐻 

Yeah, this feature would be really nice!

Saw that you already started implementing it so feel free to submit a PR and I'm happy to review.

One question would be which multipart field to use for that. I think it can be something like:

```sh
curl -F "oneshot_url=<url>" "<server_address>"
```

**Comment by vihu** [comment]
> Hey! bear
> 
> Yeah, this feature would be really nice!
> 
> Saw that you already started implementing it so feel free to submit a PR and I'm happy to review.
> 
> One question would be which multipart field to use for that. I think it can be something like:
> 
> ```shell
> curl -F "oneshot_url=<url>" "<server_address>"
> ```

Been a bit busy past few days, but yeah, I'll try to get it done hopefully by next week and submit a PR for you to review. Glad you like the feature request!

**Comment by orhun** [comment]
Looking forward to it!
