### ISSUE TITLE
Add web UI

### ISSUE THREAD

**Issue by magikid** [orhun/rustypaste#39]
It would be super handy for when I’m on mobile to have a basic web interface where I could give the application a URL or file and get back a link.

**Comment by orhun** [comment]
I don't have enough time or resources to implement this for now but I agree that it would be pretty nice to have a web UI. Not sure if we should have that in this repository though, maybe I can create `rustypaste` organization in the future and have a separate repository for that. (e.g. splitting things as `rustypaste-server` and `rustypaste-web`)

**Comment by magikid** [comment]
I've been working on this in my fork and I think with a single change users could be empowered to do this themselves (or not).   If the content type of the landing page could be either changed or configurable to `text/html` then a user could update the landing page config option with an HTML interface.

Would you be open to a PR to make the landing page content type user configurable?

**Comment by orhun** [comment]
Thank you for the PR! Would you mind sharing an example how you use this new content type feature? Adding an example to the repository would be also nice!

**Comment by magikid** [comment]
Yes, I meant to add some docs about it but you merged that PR in so quickly 😄

I’ll open another one this week with an example.

**Comment by orhun** [comment]
Cool, thank you! I will wait for that one until the next release then. 🐻
