### ISSUE TITLE
Argument support

### ISSUE THREAD

**Issue by seqizz** [orhun/rustypaste#5]
First of all, thanks for this, looks really useful.

I've packaged it and might make a nixos module out of this, but I have a small suggestion if you'd consider; cmdline arguments/parameters. Configuration options are not too many, so it might be helpful to override a 'default configuration' via arguments. Plus it can help later probably, e.g. having a `--version`.

**Comment by orhun** [comment]
Hello!

Every entry in the configuration file can be overrided via env. e.g.

```sh
PASTE__RANDOM_URL__TYPE=alphanumeric
PASTE__RANDOM_URL__LENGTH=8
```

What is your use case for having command-line arguments other than `--version`?

**Comment by seqizz** [comment]
Oh nice, didn't know that. :+1: 

> What is your use case for having command-line arguments other than --version?

Just convenience I guess, creating a config file and pointing it is a bit more work than just passing those as env/arguments.

Also, not sure if this is a bug, but apparently sending unknown file types can cause `content-type: application/octet-stream` to be served.
Is this intentional? If yes, is there a way to enforce a default type? (I'd love to see https://paste.gurkan.in/emerging-stag.nix as text file directly, instead of downloading :eyes:)

Thanks again

**Comment by seqizz** [comment]
Btw, I'm working around above problem like this for now, maybe someone else would find it useful:
```
function rpaste() {
    # Check if this is a pipe or not
    if [ ! -t 0 ]; then
        # Pipe, create temp file and send
        rm -f /tmp/pastedfile.txt
        while IFS= read -r line; do
            printf '%s\n' "$line" >> /tmp/pastedfile.txt
        done
        FILENAME=/tmp/pastedfile.txt
    else
        if ! [[ "$1" == *.txt ]]; then
            # We really need txt
            cp "$1" /tmp/pastedfile.txt
            FILENAME=/tmp/pastedfile.txt
        else
            FILENAME="$1"
        fi
    fi
    curl -F "file=@$FILENAME" -H "Authorization: mytoken" "https://mypastehost"
}
```

Feel free to close if `octet-stream` is the desired one for all cases :crossed_fingers:

**Comment by orhun** [comment]
> Just convenience I guess, creating a config file and pointing it is a bit more work than just passing those as env/arguments.

I see, maybe in the future :) (feel free to submit a PR though)

> Also, not sure if this is a bug, but apparently sending unknown file types can cause `content-type: application/octet-stream` to be served.
> Is this intentional? If yes, is there a way to enforce a default type? (I'd love to see https://paste.gurkan.in/emerging-stag.nix as text file directly, instead of downloading eyes)

It is not intentional. In fact, this was a thing that I was meaning to fix. [0x0](https://github.com/mia-0/0x0) has a similar issue and it supports overriding the MIME types.

So I pushed 03348cb38f4bc11e27a6c31f646550a009810fe4, which adds the following configuration entry to the `[paste]` section:

```toml
mime_override = [
    { mime = "image/jpeg", regex = "^.*\\.jpg$" },
    { mime = "text/plain", regex = "^.*\\.(log|txt|diff)$" },
]
```

This is hopefully going to be useful for most of the MIME type related issues.

Additionally, I pushed e7ad855f4d6aa0218d69ed0030bcfcb4a82ecde8 which is also something useful I think.

> Btw, I'm working around above problem like this for now, maybe someone else would find it useful:

Thanks for the script 🐰 

> Feel free to close if `octet-stream` is the desired one for all cases crossed_fingers

Last time I checked this issue was about command-line arguments 😄 So it's going to be stay open until that's done. I will be adding them via `structopt` in the future hopefully.

**Comment by orhun** [comment]
It looks like this is not going to happen anytime soon. Closing!
