### ISSUE TITLE
Idea: Deduplication/hashing/hardlinking

### ISSUE THREAD

**Issue by seqizz** [orhun/rustypaste#7]
Hi again,

I realized when same file uploaded twice, takes twice amount of place on the server. Just as an idea (possible with a strong-enough-to-trust hashing):

Hardlinks can be used on server side and/or client side can send the hash before uploading file to the server (and it can return the same/a brand new URL). This might save some bandwidth & disk space.

Of course there is security side of the things, like guessing attacks etc, but whole thing can be optional depending on the use case.

**Comment by orhun** [comment]
Hello!

I implemented this using the SHA256sums of the uploaded files. Now you can disable "duplicate uploads" by specifying the following option in the configuration file:

```toml
[paste]
duplicate_files = false
```

Feel free to try it out and close the issue if everything works fine :)
